version: '3.7'

services:
  app:
    image: app:latest
    ports:
      - 8082:8080
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.http.routers.app.rule=Method(`GET`)"
        - "traefik.http.services.app_app.loadbalancer.server.port=8082"
    networks:
      - trafk
networks:
  trafk:
     external: true