version: '3'
services:
  datadog:
    image: gcr.io/datadoghq/agent:latest
    environment:
     - DD_API_KEY=DD_API_KEY
     - DD_SITE=datadoghq.com
     - DD_PROCESS_AGENT_ENABLED=true
     - DD_SYSTEM_PROBE_ENABLED=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /etc/passwd:/etc/passwd:ro
     - /sys/kernel/debug:/sys/kernel/debug 
    cap_add:
     - SYS_ADMIN
     - SYS_RESOURCE
     - SYS_PTRACE
     - NET_ADMIN
     - IPC_LOCK
    security_opt:
     - apparmor:unconfined