version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
      network.publish_host: _eth0_
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

  filebeat:
    image: bargenson/filebeat
    restart: unless-stopped
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    environment:
     - LOGSTASH_HOST=logstash
     - LOGSTASH_PORT=5044
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - elk

configs:
  elastic_config:
    file: ./elk-conf/elasticsearch.yml
  logstash_config:
    file: ./elk-conf/logstash.yml
  logstash_pipeline:
    file: ./elk-conf/logstash.conf
  kibana_config:
    file: ./elk-conf/kibana.yml

networks:
  elk:
    driver: overlay