version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:alpine
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environments:
      - JAVA_OPTS='-Xmx256M'
volumes:
  jenkins_data:
