version: '3.7'

services:
  reverse-proxy:
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker --providers.docker.swarmMode=true
    ports:
      - 80:80
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - trafk
networks:
  trafk:
    driver: overlay
    attachable: true
